### ISSUE TITLE
最新版的源码和release是不是对不上？

### ISSUE THREAD

**Issue by UVJkiNTQ** [AI-lumin/Biliuper#5]
源码运行报错:
$ python mainpy.py
Traceback (most recent call last):
  File "/mnt/green/up/mainpy.py", line 12, in <module>
    import delete
  File "/mnt/green/up/delete.py", line 16, in <module>
    backup_path = dojson.get_set()['backup_path']
  File "/mnt/green/up/dojson.py", line 14, in get_set
    data = read_json(json_path)['sets']

问题在get_set()这个函数。

biliup代码用的collections的import也有点问题
应为
from collections.abc import
找了biliup的代码库覆盖了就修复了

**Comment by MrZhongzq** [comment]
老哥好。抱歉打扰了，我fork了代码然后用最新的biliup覆盖了原作者的代码。我问问我如何编译成exe文件。
